export const room = [

];

export const subjects = [
    { id: 'all', name: 'All' },
  { id: 'math', name: 'Mathematics' },
  { id: 'ela', name: 'English Language Arts' },
  { id: 'science', name: 'Science' },
  { id: 'social', name: 'Social Studies' },
  {id: 'other', name: "Other"}
];

export const roomData = [
    {
        id: 1,
        title: 'Math Study Group',
        subject: 'math',
        host: 'John Doe',
        date: '2023-10-21',
        startTime: '09:00',
        endTime: '11:00',
      },
      {
        id: 2,
        title: 'Science Discussion',
        subject: 'science',
        host: 'Jane Smith',
        date: '2023-10-22',
        startTime: '15:00',
        endTime: '17:00',
      },
      {
        id: 3,
        title: 'English Language Arts Workshop',
        subject: 'ela',
        host: 'Alice Johnson',
        date: '2023-10-24',
        startTime: '13:00',
        endTime: '14:30',
      },
      {
        id: 4,
        title: 'Social Studies Seminar',
        subject: 'social',
        host: 'Bob Wilson',
        date: '2023-10-26',
        startTime: '10:30',
        endTime: '12:00',
      },
      {
        id: 5,
        title: 'Mathematics Quiz Night',
        subject: 'math',
        host: 'Eva Brown',
        date: '2023-10-19',
        startTime: '18:30',
        endTime: '20:00',
      },
      {
        id: 6,
        title: 'Science Fair Prep',
        subject: 'science',
        host: 'Karen Davis',
        date: '2023-10-27',
        startTime: '14:00',
        endTime: '16:00',
      },
      {
        id: 7,
        title: 'Literary Analysis Workshop',
        subject: 'ela',
        host: 'James Clark',
        date: '2023-10-28',
        startTime: '11:30',
        endTime: '13:00',
      },
      {
        id: 8,
        title: 'History Discussion Group',
        subject: 'social',
        host: 'Linda Adams',
        date: '2023-10-30',
        startTime: '16:30',
        endTime: '18:00',
      },
      {
        id: 9,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-15',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 10,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-16',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 11,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-17',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 12,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-18',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 13,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-19',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 9,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-21',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 10,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-22',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 11,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-23',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 12,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-24',
        startTime: '00:00',
        endTime: '23:59',
      },
      {
        id: 13,
        title: 'Pomodoro Group (All Day)',
        subject: 'other',
        host: 'Community',
        date: '2023-10-25',
        startTime: '00:00',
        endTime: '23:59',
      },
    // Add more room entries as needed
  ];